#!/bin/bash

# Custom general exports which scripts can source

# General exports
export BROWSER=firefox
export SHELL=zsh
export TERMINAL=st
export EDITOR=nvim
export MANPAGER="bat --paging=always"

# Paths
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=/etc/fos/bin:$PATH
export PATH=/etc/fos/statusbar:$PATH

# Custom use exports
export WALLPAPER=$HOME/.config/wallpaper/bb.jpg

# Aliases
alias b="bat"
alias v="nvim"
alias c="nvim +Calendar"
alias lgrep="grep --color=auto --line-buffered"
alias cf="copyfile"
alias cpd="copydir"
alias grep="grep --color=auto"
alias l="logo-ls -D"
alias m="make"
alias mc="rm -f config.h ; make"
alias mi="sudo make install"
alias fb="fbrightness"
# serversync
alias ssync="rsync -zav -e 'ssh -p 1337' --progress"
