#!/bin/bash

# Custom general exports which scripts can source

# General exports
export BROWSER=firefox
export SHELL=zsh
export TERMINAL=st
export EDITOR=nvim
export MANPAGER="bat --paging=always"

# Paths
export PATH=$PATH:$HOME/bin:/usr/local/bin
export PATH=$PATH:/etc/fos/bin
export PATH=$PATH:/etc/fos/statusbar
export PATH=$PATH:/usr/local/go/bin

# Custom use exports
export WALLPAPER=/etc/fos/wallpapers/bastion.png

# Aliases
alias b="bat"
alias v="nvim"
alias c="nvim +Calendar"
alias lgrep="grep --color=auto --line-buffered"
alias cf="copyfile"
alias cpd="copydir"
alias grep="grep --color=auto"
alias l="logo-ls -D"
alias m="make"
alias mc="rm -f config.h ; make"
alias mi="sudo make install"
alias fb="fbrightness"
alias allmod="find /lib/modules/$(uname -r) -type f -name '*.ko*'"
alias ra="ranger"

# serversync (very custom)
alias ssync="rsync -zav -e 'ssh -p 1337' --progress"
