#!/bin/bash
# Will be called on startup by .xinitrc

# TODO: Make this a systemd file for startup (service)

# Wait for dwm to startup
while ! pgrep -x dwm > /dev/null
do
	sleep .2
done

# Source aliases and path for this script
source /etc/fos/config/fos_shell_settings

# Set wallpaper
feh --bg-scale ${WALLPAPER}

# Start notification daemon
dunst &

# Start keep_alive script (Application monitoring)
while true
do
    bash /etc/fos/system/falive &> /dev/null
done
